# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9216469763d65bcf218cdf63062cf86c2609e7fa6de0f7fd21e356113fd01528d098a06bb2acc2fa21237a07d900194cc29f497ee3ae1ddb7994906b0a3213e4
  aust_post_API: d390555a-533e-4b84-98ce-0015ff499ace

test:
  secret_key_base: beb3637fe70127045994bb6948179afe61f3a8ad8a0a4c7535bfef6c31190915f0a885273d6d69d131048ab1aee5e52e281f8dcf9081552598ec1640f85630c5
  aust_post_API: d390555a-533e-4b84-98ce-0015ff499ace

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
