@power = Product.find_or_create_by(name: "Ethical Power")
@super = Product.find_or_create_by(name: "Ethical Super")
@solar = Product.find_or_create_by(name: "Ethical Solar")
@homeloans = Product.find_or_create_by(name: "Ethical Homeloans")

@powershop = Provider.find_or_create_by(name: "Powershop")
@diamond = Provider.find_or_create_by(name: "Diamond")
@good_super = Provider.find_or_create_by(name: "Good Super")
@future_super = Provider.find_or_create_by(name: "Future Super")
@australian_ethical = Provider.find_or_create_by(name: "Australian Ethical")
@shinehub = Provider.find_or_create_by(name: "ShineHub")
@ethical_homeloans = Provider.find_or_create_by(name: "Ethical Homeloans")

@vic = State.find_or_create_by(name: "Victoria", abbr: "VIC")
@nsw = State.find_or_create_by(name: "New South Wales", abbr: "NSW")
@sa = State.find_or_create_by(name: "South Australia", abbr: "SA")
@qld = State.find_or_create_by(name: "Queensland", abbr: "QLD")
@wa = State.find_or_create_by(name: "Western Australia", abbr: "WA")
@tas = State.find_or_create_by(name: "Tasmania", abbr: "TAS")
@act = State.find_or_create_by(name: "Australian Capital Territory", abbr: "ACT")
@nt = State.find_or_create_by(name: "Northern Territory", abbr: "NT")

ProviderProduct.find_or_create_by(provider_id: @powershop.id, product_id: @power.id)
ProviderProduct.find_or_create_by(provider_id: @diamond.id, product_id: @power.id)
ProviderProduct.find_or_create_by(provider_id: @good_super.id, product_id: @super.id)
ProviderProduct.find_or_create_by(provider_id: @future_super.id, product_id: @super.id)
ProviderProduct.find_or_create_by(provider_id: @australian_ethical.id, product_id: @super.id)
ProviderProduct.find_or_create_by(provider_id: @shinehub.id, product_id: @solar.id)
ProviderProduct.find_or_create_by(provider_id: @ethical_homeloans.id, product_id: @homeloans.id)

ProviderState.find_or_create_by(provider_id: @powershop.id, state_id: @vic.id)
ProviderState.find_or_create_by(provider_id: @powershop.id, state_id: @nsw.id)
ProviderState.find_or_create_by(provider_id: @diamond.id, state_id: @vic.id)
ProviderState.find_or_create_by(provider_id: @diamond.id, state_id: @nsw.id)
ProviderState.find_or_create_by(provider_id: @diamond.id, state_id: @sa.id)
ProviderState.find_or_create_by(provider_id: @diamond.id, state_id: @qld.id)
ProviderState.find_or_create_by(provider_id: @good_super.id, state_id: @vic.id)
ProviderState.find_or_create_by(provider_id: @good_super.id, state_id: @nsw.id)
ProviderState.find_or_create_by(provider_id: @good_super.id, state_id: @sa.id)
ProviderState.find_or_create_by(provider_id: @good_super.id, state_id: @qld.id)
ProviderState.find_or_create_by(provider_id: @future_super.id, state_id: @vic.id)
ProviderState.find_or_create_by(provider_id: @future_super.id, state_id: @nsw.id)
ProviderState.find_or_create_by(provider_id: @future_super.id, state_id: @sa.id)
ProviderState.find_or_create_by(provider_id: @future_super.id, state_id: @qld.id)
ProviderState.find_or_create_by(provider_id: @australian_ethical.id, state_id: @vic.id)
ProviderState.find_or_create_by(provider_id: @australian_ethical.id, state_id: @nsw.id)
ProviderState.find_or_create_by(provider_id: @australian_ethical.id, state_id: @sa.id)
ProviderState.find_or_create_by(provider_id: @australian_ethical.id, state_id: @qld.id)
ProviderState.find_or_create_by(provider_id: @shinehub.id, state_id: @vic.id)
ProviderState.find_or_create_by(provider_id: @shinehub.id, state_id: @nsw.id)
ProviderState.find_or_create_by(provider_id: @shinehub.id, state_id: @sa.id)
ProviderState.find_or_create_by(provider_id: @shinehub.id, state_id: @qld.id)
ProviderState.find_or_create_by(provider_id: @ethical_homeloans.id, state_id: @vic.id)
ProviderState.find_or_create_by(provider_id: @ethical_homeloans.id, state_id: @nsw.id)
ProviderState.find_or_create_by(provider_id: @ethical_homeloans.id, state_id: @sa.id)
ProviderState.find_or_create_by(provider_id: @ethical_homeloans.id, state_id: @qld.id)